# Site settings
name: Sarthak Munshi
title: Sarthak Munshi #website title
description: > # this means to ignore newlines until "baseurl:"
  Home of Sarthak
url: #https://kuoa.github.io # the base hostname & protocol for your site
baseurl: # the sub-path of your site, e.g. /blog/

disqus_shortname: saru95 # leave empty if you don't want comments
google_analytics: true #if set to "true" modify the google_analytycs.html, set to false otherwise

# Links settings
links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
    external:     false
  - name:         Research
    url:          /work
    external:     false
  - name:         Contact
    url:          /contact
    external:     false

# Build settings
markdown: kramdown 
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"] 
